// Typed access to the vendored CLI facts document (src/data/cli-facts.json).
//
// The JSON is generated by `gofasta facts --json` at the CLI version pinned
// in `.cli-version` (repo root). CI re-generates it from that exact release
// and fails on any difference, so values read here are guaranteed to match
// the released CLI the docs describe. Docs render volatile numbers through
// the <Fact> atom (which calls getFact) instead of hard-coding them.
import facts from "@/data/cli-facts.json";

/** The vendored facts document, typed structurally from the JSON itself. */
export const cliFacts = facts;

/**
 * Resolve a dotted path (with optional `[N]` array indexes) through the
 * facts document and return the scalar at that location as a string.
 *
 * Throws on unknown paths or non-scalar leaves — a typo'd `<Fact name>`
 * must fail `next build`, not silently render nothing.
 */
export function getFact(path: string): string {
  let current: unknown = facts;
  for (const segment of path.split(".")) {
    const match = /^([^[\]]+)((?:\[\d+\])*)$/.exec(segment);
    if (!match) {
      throw new Error(`cli-facts: malformed path segment "${segment}" in "${path}"`);
    }
    const [, key, indexPart] = match;
    if (typeof current !== "object" || current === null || Array.isArray(current)) {
      throw new Error(`cli-facts: "${key}" in "${path}" is not reachable — parent is not an object`);
    }
    current = (current as Record<string, unknown>)[key];
    if (current === undefined) {
      throw new Error(`cli-facts: unknown field "${key}" in "${path}"`);
    }
    for (const rawIndex of indexPart.match(/\d+/g) ?? []) {
      if (!Array.isArray(current)) {
        throw new Error(`cli-facts: "${segment}" in "${path}" indexes a non-array`);
      }
      current = current[Number(rawIndex)];
      if (current === undefined) {
        throw new Error(`cli-facts: index out of range in "${segment}" of "${path}"`);
      }
    }
  }
  if (
    typeof current !== "string" &&
    typeof current !== "number" &&
    typeof current !== "boolean"
  ) {
    throw new Error(`cli-facts: "${path}" resolves to a non-scalar value`);
  }
  return String(current);
}
