/**
 * Centralized SEO keywords for every page on the site.
 *
 * Base keywords are appended to every page automatically.
 * Page-specific keywords are keyed by their URL path (without trailing slash).
 */

const BASE_KEYWORDS = [
  "Go",
  "Golang",
  "Gofasta",
  "web framework",
  "backend",
];

const PAGE_KEYWORDS: Record<string, string[]> = {
  // Landing
  "/": [
    "code generation",
    "scaffolding",
    "CLI",
    "REST API",
    "GraphQL",
    "Go web services",
    "production-ready",
    // Agent-native differentiator — captures searches for
    // "Go Claude Code", "Go AI coding agent", "agent-native Go", etc.
    "AI coding agent",
    "agent-native",
    "Claude Code",
    "Cursor",
    "OpenAI Codex",
    "Aider",
    "Windsurf",
    "AGENTS.md",
    "llms.txt",
    "LLM-friendly documentation",
  ],

  // Docs index
  "/docs": [
    "documentation",
    "API reference",
    "guides",
    "CLI reference",
    "AI coding agent",
    "AGENTS.md",
    "llms.txt",
  ],

  // White Paper
  "/docs/white-paper": [
    "white paper",
    "technical paper",
    "architecture",
    "design principles",
    "code generation",
    "dependency injection",
    "Google Wire",
    "GORM",
    "chi router",
    "compile-time DI",
    "scaffolding",
    "REST API",
    "GraphQL",
    "authentication",
    "JWT",
    "RBAC",
    "background jobs",
    "task queue",
    "asynq",
    "observability",
    "Prometheus",
    "OpenTelemetry",
    "circuit breaker",
    "resilience",
    "retry",
    "database migrations",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "deployment",
    "Docker",
    "CI/CD",
    "health checks",
    "middleware",
    "CORS",
    "rate limiting",
    "email",
    "notifications",
    "WebSocket",
    "caching",
    "Redis",
    "feature flags",
    "i18n",
    "encryption",
    "sessions",
    "file storage",
    "S3",
    "validation",
    "open source",
    "MIT license",
    "Go toolkit",
    "Go web services",
    "production-ready",
    "batteries-included",
    // Agent-native design principles (§2.7 + §4.5 of the whitepaper)
    // — highest-priority page for capturing "Go AI coding agent"
    // intent searches.
    "AI coding agent",
    "agent-native",
    "Claude Code",
    "Cursor",
    "OpenAI Codex",
    "Aider",
    "Windsurf",
    "AGENTS.md",
    "llms.txt",
    "llms-full.txt",
    "structured errors",
    "stable error codes",
    "--json flag",
  ],

  // Getting Started
  "/docs/getting-started/introduction": [
    "introduction",
    "getting started",
    "overview",
    "why Gofasta",
    "AI coding agent",
    "agent-native",
    "AGENTS.md",
    "Claude Code",
    "Cursor",
  ],
  "/docs/getting-started/installation": [
    "install",
    "setup",
    "CLI install",
    "Go install",
  ],
  "/docs/getting-started/quick-start": [
    "quick start",
    "tutorial",
    "first project",
    "hello world",
  ],
  "/docs/getting-started/project-structure": [
    "project structure",
    "directory layout",
    "folder structure",
    "project organization",
  ],

  // Guides
  "/docs/guides/rest-api": [
    "REST API",
    "HTTP handlers",
    "routes",
    "endpoints",
    "JSON API",
  ],
  "/docs/guides/graphql": [
    "GraphQL",
    "resolvers",
    "schema",
    "queries",
    "mutations",
  ],
  "/docs/guides/database-and-migrations": [
    "database",
    "migrations",
    "SQL",
    "PostgreSQL",
    "schema migrations",
  ],
  "/docs/guides/authentication": [
    "authentication",
    "auth",
    "JWT",
    "login",
    "sessions",
  ],
  "/docs/guides/code-generation": [
    "code generation",
    "scaffolding",
    "generators",
    "boilerplate",
  ],
  "/docs/guides/background-jobs": [
    "background jobs",
    "workers",
    "async tasks",
    "job queue",
  ],
  "/docs/guides/email-and-notifications": [
    "email",
    "notifications",
    "SMTP",
    "mailer",
    "templates",
  ],
  "/docs/guides/testing": [
    "testing",
    "unit tests",
    "integration tests",
    "test utilities",
  ],
  "/docs/guides/debugging": [
    "debugging",
    "debug dashboard",
    "trace waterfall",
    "OpenTelemetry",
    "pprof",
    "N+1 detection",
    "per-request logs",
    "request replay",
    "call stack snapshots",
    "devtools build tag",
    "GORM query capture",
    "slog",
    "panic recovery",
    "cache inspector",
    "EXPLAIN plans",
    "HAR export",
  ],
  "/docs/guides/deployment": [
    "deployment",
    "Docker",
    "production",
    "CI/CD",
    "hosting",
  ],
  "/docs/guides/configuration": [
    "configuration",
    "environment variables",
    "config files",
    "settings",
  ],

  // CLI Reference
  "/docs/cli-reference/new": [
    "CLI",
    "new project",
    "create project",
    "gofasta new",
  ],
  "/docs/cli-reference/init": [
    "CLI",
    "init",
    "initialize",
    "gofasta init",
  ],
  "/docs/cli-reference/dev": [
    "CLI",
    "dev server",
    "development",
    "hot reload",
    "gofasta dev",
  ],
  "/docs/cli-reference/debug": [
    "CLI",
    "debugging",
    "debug",
    "trace waterfall",
    "pprof",
    "N+1 detection",
    "request replay",
    "HAR export",
    "EXPLAIN",
    "slog",
    "goroutine inspector",
    "gofasta debug",
    "devtools",
    "OpenTelemetry",
  ],
  "/docs/cli-reference/ai": [
    "CLI",
    "AI coding agent",
    "agent-native",
    "AI installer",
    "Claude Code",
    "Cursor",
    "OpenAI Codex",
    "Aider",
    "Windsurf",
    "AGENTS.md",
    "agent configuration",
    "permission allowlist",
    "slash commands",
    "gofasta ai",
    "gofasta ai claude",
    "gofasta ai cursor",
    "gofasta ai codex",
    "gofasta ai aider",
    "gofasta ai windsurf",
  ],
  "/docs/cli-reference/verify": [
    "CLI",
    "verify",
    "preflight",
    "quality gate",
    "gofmt",
    "go vet",
    "golangci-lint",
    "race detector",
    "Wire drift",
    "structured output",
    "agent-friendly",
    "gofasta verify",
  ],
  "/docs/cli-reference/status": [
    "CLI",
    "status",
    "drift detection",
    "Wire drift",
    "Swagger drift",
    "pending migrations",
    "generated files",
    "agent-friendly",
    "gofasta status",
  ],
  "/docs/cli-reference/inspect": [
    "CLI",
    "inspect",
    "AST",
    "resource introspection",
    "structured output",
    "AI coding agent",
    "agent-friendly",
    "gofasta inspect",
  ],
  "/docs/cli-reference/do": [
    "CLI",
    "workflow",
    "named workflow",
    "command chain",
    "agent workflow",
    "new-rest-endpoint",
    "rebuild",
    "fresh-start",
    "clean-slate",
    "health-check",
    "gofasta do",
  ],
  "/docs/cli-reference/config": [
    "CLI",
    "config",
    "config schema",
    "JSON Schema",
    "config.yaml",
    "config validation",
    "agent-friendly",
    "gofasta config",
    "gofasta config schema",
  ],
  "/docs/cli-reference/migrate": [
    "CLI",
    "migrate",
    "database migrations",
    "gofasta migrate",
  ],
  "/docs/cli-reference/seed": [
    "CLI",
    "seed",
    "database seeding",
    "test data",
    "gofasta seed",
  ],
  "/docs/cli-reference/serve": [
    "CLI",
    "serve",
    "production server",
    "gofasta serve",
  ],
  "/docs/cli-reference/wire": [
    "CLI",
    "wire",
    "dependency injection",
    "gofasta wire",
  ],
  "/docs/cli-reference/swagger": [
    "CLI",
    "swagger",
    "OpenAPI",
    "API docs",
    "gofasta swagger",
  ],
  "/docs/cli-reference/routes": [
    "CLI",
    "routes",
    "REST routes",
    "route listing",
    "API routes",
    "gofasta routes",
  ],
  "/docs/cli-reference/console": [
    "CLI",
    "console",
    "REPL",
    "Go REPL",
    "yaegi",
    "interactive",
    "gofasta console",
  ],
  "/docs/cli-reference/doctor": [
    "CLI",
    "doctor",
    "diagnostics",
    "environment check",
    "prerequisites",
    "gofasta doctor",
  ],
  "/docs/cli-reference/upgrade": [
    "CLI",
    "upgrade",
    "self-update",
    "CLI upgrade",
    "gofasta upgrade",
  ],
  "/docs/cli-reference/version": [
    "CLI",
    "version",
    "build info",
    "gofasta version",
  ],
  "/docs/cli-reference/db": [
    "CLI",
    "database",
    "db reset",
    "database management",
    "gofasta db",
  ],
  "/docs/cli-reference/deploy": [
    "CLI",
    "deploy",
    "deployment",
    "VPS deployment",
    "Docker deployment",
    "gofasta deploy",
  ],

  // CLI Reference - Generate
  "/docs/cli-reference/generate/scaffold": [
    "scaffold",
    "generate",
    "CRUD",
    "full resource",
    "gofasta generate",
  ],
  "/docs/cli-reference/generate/model": [
    "generate model",
    "ORM",
    "database model",
    "struct",
  ],
  "/docs/cli-reference/generate/repository": [
    "generate repository",
    "data access",
    "repository pattern",
  ],
  "/docs/cli-reference/generate/service": [
    "generate service",
    "business logic",
    "service layer",
  ],
  "/docs/cli-reference/generate/controller": [
    "generate controller",
    "HTTP handler",
    "request handler",
  ],
  "/docs/cli-reference/generate/dto": [
    "generate DTO",
    "data transfer object",
    "request body",
    "response body",
  ],
  "/docs/cli-reference/generate/migration": [
    "generate migration",
    "database migration",
    "schema change",
  ],
  "/docs/cli-reference/generate/route": [
    "generate route",
    "HTTP route",
    "endpoint",
    "routing",
  ],
  "/docs/cli-reference/generate/resolver": [
    "generate resolver",
    "GraphQL resolver",
    "query resolver",
  ],
  "/docs/cli-reference/generate/provider": [
    "generate provider",
    "dependency injection",
    "provider pattern",
  ],
  "/docs/cli-reference/generate/job": [
    "generate job",
    "background job",
    "worker",
    "async task",
  ],
  "/docs/cli-reference/generate/task": [
    "generate task",
    "scheduled task",
    "cron job",
    "periodic task",
  ],
  "/docs/cli-reference/generate/email-template": [
    "generate email template",
    "email",
    "HTML email",
    "mail template",
  ],

  // API Reference
  "/docs/api-reference/config": [
    "config API",
    "configuration",
    "database setup",
    "environment",
  ],
  "/docs/api-reference/auth": [
    "auth API",
    "authentication",
    "authorization",
    "JWT",
    "tokens",
  ],
  "/docs/api-reference/cache": [
    "cache API",
    "caching",
    "Redis",
    "in-memory cache",
  ],
  "/docs/api-reference/errors": [
    "errors API",
    "error handling",
    "HTTP errors",
    "error responses",
  ],
  "/docs/api-reference/http-utilities": [
    "HTTP utilities",
    "request helpers",
    "response helpers",
    "HTTP client",
  ],
  "/docs/api-reference/logger": [
    "logger API",
    "logging",
    "structured logging",
    "log levels",
  ],
  "/docs/api-reference/mailer": [
    "mailer API",
    "email sending",
    "SMTP",
    "email templates",
  ],
  "/docs/api-reference/middleware": [
    "middleware API",
    "HTTP middleware",
    "request pipeline",
    "interceptors",
  ],
  "/docs/api-reference/models": [
    "models API",
    "ORM",
    "database models",
    "structs",
    "schema",
  ],
  "/docs/api-reference/notifications": [
    "notifications API",
    "push notifications",
    "alerts",
    "messaging",
  ],
  "/docs/api-reference/queue": [
    "queue API",
    "message queue",
    "job queue",
    "async processing",
  ],
  "/docs/api-reference/resilience": [
    "resilience API",
    "circuit breaker",
    "retry",
    "fault tolerance",
  ],
  "/docs/api-reference/scheduler": [
    "scheduler API",
    "cron",
    "scheduled tasks",
    "periodic jobs",
  ],
  "/docs/api-reference/storage": [
    "storage API",
    "file storage",
    "uploads",
    "S3",
    "file system",
  ],
  "/docs/api-reference/validators": [
    "validators API",
    "validation",
    "input validation",
    "request validation",
  ],
  "/docs/api-reference/websocket": [
    "WebSocket API",
    "real-time",
    "WebSocket",
    "bidirectional",
  ],
  "/docs/api-reference/i18n": [
    "i18n API",
    "internationalization",
    "localization",
    "translations",
  ],
  "/docs/api-reference/observability": [
    "observability API",
    "metrics",
    "tracing",
    "OpenTelemetry",
    "monitoring",
  ],
  "/docs/api-reference/feature-flags": [
    "feature flags API",
    "feature toggles",
    "feature management",
    "rollouts",
  ],
  "/docs/api-reference/sessions": [
    "sessions API",
    "session management",
    "cookies",
    "session store",
  ],
  "/docs/api-reference/encryption": [
    "encryption API",
    "cryptography",
    "hashing",
    "AES",
    "secrets",
  ],
  "/docs/api-reference/seeds": [
    "seeds API",
    "database seeding",
    "test data",
    "fixtures",
  ],
  "/docs/api-reference/types": [
    "types API",
    "TypeScript types",
    "type definitions",
    "interfaces",
  ],
  "/docs/api-reference/utils": [
    "utils API",
    "utilities",
    "helper functions",
    "common utils",
  ],
  "/docs/api-reference/health": [
    "health API",
    "health check",
    "readiness",
    "liveness",
    "monitoring",
  ],
  "/docs/api-reference/test-utilities": [
    "test utilities API",
    "testing helpers",
    "test fixtures",
    "mock helpers",
  ],
};

/**
 * Returns the combined keywords for a given URL path.
 * Base keywords are always included.
 */
export function getKeywordsForPath(path: string): string[] {
  const pageKeywords = PAGE_KEYWORDS[path] ?? [];
  return [...BASE_KEYWORDS, ...pageKeywords];
}
