const meta = {
  config: "Config",
  logger: "Logger",
  errors: "Errors",
  models: "Models",
  "http-utilities": "HTTP Utilities",
  middleware: "Middleware",
  auth: "Auth",
  cache: "Cache",
  storage: "Storage",
  mailer: "Mailer",
  notifications: "Notifications",
  websocket: "WebSocket",
  scheduler: "Scheduler",
  queue: "Queue",
  resilience: "Resilience",
  validators: "Validators",
  i18n: "i18n",
  observability: "Observability",
  "feature-flags": "Feature Flags",
  sessions: "Sessions",
  encryption: "Encryption",
  seeds: "Seeds",
  types: "Types",
  utils: "Utils",
  health: "Health",
  "test-utilities": "Test Utilities",
};
