import type { MetadataRoute } from "next";
import { existsSync, readdirSync, statSync } from "fs";
import { join } from "path";

const BASE_URL = "https://gofasta.dev";

// getMdxPaths walks an MDX content directory and emits URL paths for
// every .mdx file under it. The mapping mirrors Nextra's content
// routing — `index.mdx` resolves to its parent slug, every other file
// resolves to its slug.
//
// `urlPrefix` is the URL-space root the directory maps to. For docs
// pass "/docs"; for the blog pass "/blog". Previously this prefix was
// hardcoded; making it a parameter is what lets the same walker
// power both surfaces from one source.
function getMdxPaths(
  dir: string,
  urlPrefix: string,
  basePath: string = "",
): string[] {
  const paths: string[] = [];
  if (!existsSync(dir)) return paths;
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      paths.push(...getMdxPaths(fullPath, urlPrefix, `${basePath}/${entry}`));
    } else if (entry.endsWith(".mdx")) {
      const slug = entry.replace(/\.mdx$/, "");
      const urlPath =
        slug === "index" && basePath === ""
          ? urlPrefix
          : slug === "index"
            ? `${urlPrefix}${basePath}`
            : `${urlPrefix}${basePath}/${slug}`;
      paths.push(urlPath);
    }
  }

  return paths;
}

// sitemap.xml — every page that should be discoverable by search
// engines. The home page is high priority; the section roots (`/docs`,
// `/blog`) sit one notch below; individual pages sit at 0.7. The HTML
// sitemap at /sitemap is a secondary discovery surface for humans.
export default function sitemap(): MetadataRoute.Sitemap {
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/sitemap`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
  ];

  const contentRoot = join(process.cwd(), "src", "content");

  // Docs: every MDX file under src/content/ — blog content lives at
  // the top-level `content/blog/` directory (outside Nextra's scan
  // path) so we don't filter the docs walker here.
  const docPaths = readdirSync(contentRoot)
    .filter(
      (entry) =>
        entry.endsWith(".mdx") ||
        statSync(join(contentRoot, entry)).isDirectory(),
    )
    .flatMap((entry) => {
      const fullPath = join(contentRoot, entry);
      if (statSync(fullPath).isDirectory()) {
        return getMdxPaths(fullPath, "/docs", `/${entry}`);
      }
      const slug = entry.replace(/\.mdx$/, "");
      return [slug === "index" ? "/docs" : `/docs/${slug}`];
    });

  const docPages: MetadataRoute.Sitemap = docPaths.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: path === "/docs" ? 0.9 : 0.7,
  }));

  // Blog: every MDX file under data/blog/ → /blog/<slug>. The
  // index itself (/blog) is generated by the route handler at
  // src/app/(home)/blog/page.tsx; include it explicitly here. The
  // blog content directory lives at `data/blog/` (not under any
  // `content/` path) so Nextra's catch-all — which scans both
  // `src/content/` and `content/` — doesn't double-emit each post
  // as a /docs/blog/... URL.
  const blogDir = join(process.cwd(), "data", "blog");
  const blogPaths = getMdxPaths(blogDir, "/blog");

  const blogPages: MetadataRoute.Sitemap = [];
  if (blogPaths.length > 0) {
    blogPages.push({
      url: `${BASE_URL}/blog`,
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.9,
    });
    for (const path of blogPaths) {
      blogPages.push({
        url: `${BASE_URL}${path}`,
        lastModified: new Date(),
        changeFrequency: "weekly",
        priority: 0.7,
      });
    }
  }

  return [...staticPages, ...docPages, ...blogPages];
}
