import type { MetadataRoute } from "next";
import { existsSync, readdirSync, statSync } from "fs";
import { join } from "path";
import { getAllPosts, getAllTags, getPostsByTag } from "@/lib/blog";
import { AGENT_DOC_FILES, SITE_URL } from "@/lib/seo";

// getMdxPaths walks an MDX content directory and emits URL paths for
// every .mdx file under it. The mapping mirrors Nextra's content
// routing — `index.mdx` resolves to its parent slug, every other file
// resolves to its slug.
//
// `urlPrefix` is the URL-space root the directory maps to. For docs
// pass "/docs"; for the blog pass "/blog". Previously this prefix was
// hardcoded; making it a parameter is what lets the same walker
// power both surfaces from one source.
function getMdxPaths(
  dir: string,
  urlPrefix: string,
  basePath: string = "",
): string[] {
  const paths: string[] = [];
  if (!existsSync(dir)) return paths;
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      paths.push(...getMdxPaths(fullPath, urlPrefix, `${basePath}/${entry}`));
    } else if (entry.endsWith(".mdx")) {
      const slug = entry.replace(/\.mdx$/, "");
      const urlPath =
        slug === "index" && basePath === ""
          ? urlPrefix
          : slug === "index"
            ? `${urlPrefix}${basePath}`
            : `${urlPrefix}${basePath}/${slug}`;
      paths.push(urlPath);
    }
  }

  return paths;
}

// sitemap.xml — every page that should be discoverable by search
// engines. The home page is high priority; the section roots (`/docs`,
// `/blog`) sit one notch below; individual pages sit at 0.7. The HTML
// sitemap at /sitemap is a secondary discovery surface for humans.
//
// `lastModified` precision — VERIFIABLE dates only:
//   - Blog posts use frontmatter `updatedAt ?? publishedAt` — true
//     per-post freshness so crawlers can tell which posts actually
//     changed since the last sitemap fetch.
//   - The blog index + tag pages derive from their newest post.
//   - Static pages + docs carry NO lastModified: stamping them with the
//     build time bumped every URL on every deploy, which is exactly the
//     inaccuracy Google documents as the reason it stops trusting a
//     site's lastmod. Omitting the field keeps the blog's accurate
//     values credible.
export default function sitemap(): MetadataRoute.Sitemap {
  const buildTime = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: SITE_URL,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/sitemap`,
      changeFrequency: "monthly",
      priority: 0.5,
    },
    // /llms.txt and /llms-full.txt. The sitemap protocol takes any URL
    // on the host, not just HTML, and these were the only public pages
    // on the site with no discovery path at all — no sitemap entry and
    // (until now) no hyperlink pointing at them.
    //
    // No lastModified: both files are regenerated by the prebuild
    // script on EVERY deploy, so a build-time stamp would claim the
    // content changed whenever it hadn't — the same inaccuracy the
    // docs pages above deliberately avoid.
    //
    // priority 0.5 matches /sitemap: a real discovery surface, ranked
    // below the docs pages whose content they index.
    ...AGENT_DOC_FILES.map((file) => ({
      url: `${SITE_URL}${file.path}`,
      changeFrequency: "weekly" as const,
      priority: 0.5,
    })),
  ];

  const contentRoot = join(process.cwd(), "src", "content");

  // Docs: every MDX file under src/content/ — blog content lives at
  // the top-level `content/blog/` directory (outside Nextra's scan
  // path) so we don't filter the docs walker here.
  const docPaths = readdirSync(contentRoot)
    .filter(
      (entry) =>
        entry.endsWith(".mdx") ||
        statSync(join(contentRoot, entry)).isDirectory(),
    )
    .flatMap((entry) => {
      const fullPath = join(contentRoot, entry);
      if (statSync(fullPath).isDirectory()) {
        return getMdxPaths(fullPath, "/docs", `/${entry}`);
      }
      const slug = entry.replace(/\.mdx$/, "");
      return [slug === "index" ? "/docs" : `/docs/${slug}`];
    });

  const docPages: MetadataRoute.Sitemap = docPaths.map((path) => ({
    url: `${SITE_URL}${path}`,
    changeFrequency: "weekly" as const,
    priority: path === "/docs" ? 0.9 : 0.7,
  }));

  // Blog: every published post → /blog/<slug>. Per-post lastModified
  // comes from frontmatter so crawlers can detect edits without a full
  // sitemap re-fetch loop.
  const posts = getAllPosts();
  const blogPages: MetadataRoute.Sitemap = [];
  if (posts.length > 0) {
    const newestPostDate = posts.reduce((latest, p) => {
      const d = new Date(p.updatedAt ?? p.publishedAt);
      return d > latest ? d : latest;
    }, new Date(0));
    blogPages.push({
      url: `${SITE_URL}/blog`,
      lastModified: newestPostDate,
      changeFrequency: "daily",
      priority: 0.9,
    });
    for (const post of posts) {
      blogPages.push({
        url: `${SITE_URL}/blog/${post.slug}`,
        lastModified: new Date(post.updatedAt ?? post.publishedAt),
        changeFrequency: "weekly",
        priority: 0.7,
        // Sitemap image extension: tells Google Images (and Discover)
        // which image belongs to the post without waiting for a page
        // parse.
        images: [
          post.coverUrl.startsWith("http")
            ? post.coverUrl
            : `${SITE_URL}${post.coverUrl}`,
        ],
      });
    }
  }

  // Tag archives: discoverability win — previously absent from
  // sitemap.xml so crawlers found them only via internal links.
  // lastModified = most recent post carrying that tag.
  const tagPages: MetadataRoute.Sitemap = getAllTags().map(({ tag }) => {
    const tagPosts = getPostsByTag(tag);
    const latest = tagPosts.reduce((acc, p) => {
      const d = new Date(p.updatedAt ?? p.publishedAt);
      return d > acc ? d : acc;
    }, new Date(0));
    return {
      url: `${SITE_URL}/blog/tags/${tag}`,
      lastModified: latest.getTime() > 0 ? latest : buildTime,
      changeFrequency: "weekly" as const,
      priority: 0.5,
    };
  });

  return [...staticPages, ...docPages, ...blogPages, ...tagPages];
}
